In the delete_delegation function on line 154 in Database.py, the database was checking the permission of caller admin, even though the database does not store admin permissions. This caused a KeyError and led to nothing being returned when the caller is admin. Also, line 172 was using the incorrect variable name "user_getting_rights" and has been changed to the correct name "user_losing_rights". These bug fixes have enabled the dataserver to correctly execute basic delete delegation commands.